if ((typeof(YbqlfKicGrpitDo2UHppXj$3basis$0IO$1)) == "undefined") {YbqlfKicGrpitDo2UHppXj$3basis$0IO$1 = {};
};
(function(){YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.eq_buffer_mode$91 = function(v$93,v$94){switch (v$93) { case 0: {switch (v$94) { case 0: {return true;
 break; }default: {return false;
} };
 break; }case 1: {switch (v$94) { case 1: {return true;
 break; }default: {return false;
} };
 break; }case 2: {switch (v$94) { case 2: {return true;
 break; }default: {return false;
} };
 break; } };
};
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$Io$57 = new String("Io");
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$BlockingNotSupported$58 = new String("BlockingNotSupported");
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.exn$BlockingNotSupported$58 = [YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$BlockingNotSupported$58];
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$NonblockingNotSupported$59 = new String("NonblockingNotSupported");
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.exn$NonblockingNotSupported$59 = [YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$NonblockingNotSupported$59];
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$RandomAccessNotSupported$60 = new String("RandomAccessNotSupported");
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.exn$RandomAccessNotSupported$60 = [YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$RandomAccessNotSupported$60];
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$ClosedStream$61 = new String("ClosedStream");
YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.exn$ClosedStream$61 = [YbqlfKicGrpitDo2UHppXj$3basis$0IO$1.en$ClosedStream$61];
return 0;
})();
