if ((typeof(basis$0IO$1)) == "undefined") {basis$0IO$1 = {};
};
(function(){basis$0IO$1.eq_buffer_mode$93 = function(v$95,v$96){switch (v$95) { case 0: {switch (v$96) { case 0: {return true;
 break; }default: {return false;
} };
 break; }case 1: {switch (v$96) { case 1: {return true;
 break; }default: {return false;
} };
 break; }case 2: {switch (v$96) { case 2: {return true;
 break; }default: {return false;
} };
 break; } };
};
basis$0IO$1.en$Io$59 = new String("Io");
basis$0IO$1.en$BlockingNotSupported$60 = new String("BlockingNotSupported");
basis$0IO$1.exn$BlockingNotSupported$60 = [basis$0IO$1.en$BlockingNotSupported$60];
basis$0IO$1.en$NonblockingNotSupported$61 = new String("NonblockingNotSupported");
basis$0IO$1.exn$NonblockingNotSupported$61 = [basis$0IO$1.en$NonblockingNotSupported$61];
basis$0IO$1.en$RandomAccessNotSupported$62 = new String("RandomAccessNotSupported");
basis$0IO$1.exn$RandomAccessNotSupported$62 = [basis$0IO$1.en$RandomAccessNotSupported$62];
basis$0IO$1.en$ClosedStream$63 = new String("ClosedStream");
basis$0IO$1.exn$ClosedStream$63 = [basis$0IO$1.en$ClosedStream$63];
return 0;
})();
